# Generated by Django 5.1.4 on 2024-12-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='Class',
            field=models.CharField(default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='react',
            name='DomainName',
            field=models.CharField(default='google.com', max_length=35),
        ),
        migrations.AlterField(
            model_name='react',
            name='IPAddress',
            field=models.CharField(default='192.168.1.2', max_length=35),
        ),
    ]
